import type { Severity } from '../../compliance-core/src/index.js';

export type PilotStatus = 'DRAFT' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
export type FindingClassification = 'TRUE_POSITIVE' | 'FALSE_POSITIVE' | 'NEEDS_REVIEW';
export type Pilot = { id: string; organizationId: string; name: string; status: PilotStatus; startDate: string; endDate?: string; createdAt: string; updatedAt: string; projectIds: string[]; goals: string[]; successCriteria: string[] };
export type PilotFinding = { id: string; pilotId: string; projectId: string; ruleId: string; category: string; severity: Severity; status: string; firstDetected: string; resolvedAt?: string; suppressedAt?: string; classification?: FindingClassification; classifiedAt?: string; remediationReason?: string; repositoryName?: string; language?: string };
export type PilotScan = { id: string; pilotId: string; projectId: string; status: string; timestamp: string; durationMs: number; filesScanned: number; rulesExecuted: number; pullRequest?: string; newFindings: number; aiSystemsDiscovered: number; shadowAISystems: number; controlsWithEvidence: number };
export type PilotMetrics = { repositoriesConnected: number; repositoriesScanned: number; prsScanned: number; scansCompleted: number; filesScanned: number; rulesExecuted: number; findingsGenerated: number; newFindings: number; criticalFindings: number; highFindings: number; findingsResolved: number; findingsSuppressed: number; acceptedRisks: number; averageRemediationHours: number | null; medianRemediationHours: number | null; aiSystemsDiscovered: number; shadowAISystems: number; governanceDriftFindings: number; technicalControlsWithEvidence: number; falsePositiveRate: number | null; reviewedFindings: number; truePositives: number; falsePositives: number };
export type RuleQuality = { ruleId: string; findingsGenerated: number; reviewedFindings: number; truePositives: number; falsePositives: number; needsReview: number; precision: number | null; suppressionRate: number; resolutionRate: number };
const hours = (start: string, end?: string): number | undefined => end ? Math.max(0, (Date.parse(end) - Date.parse(start)) / 3_600_000) : undefined;
export function calculatePilotMetrics(pilot: Pilot, scans: PilotScan[], findings: PilotFinding[]): PilotMetrics {
 const scopedScans = scans.filter(item => item.pilotId === pilot.id); const scopedFindings = findings.filter(item => item.pilotId === pilot.id); const completed = scopedFindings.filter(item => item.resolvedAt || item.suppressedAt); const remediation = completed.map(item => hours(item.firstDetected, item.resolvedAt ?? item.suppressedAt)).filter((item): item is number => item !== undefined).sort((a, b) => a - b); const classified = scopedFindings.filter(item => item.classification); const truePositives = classified.filter(item => item.classification === 'TRUE_POSITIVE').length; const falsePositives = classified.filter(item => item.classification === 'FALSE_POSITIVE').length;
 return { repositoriesConnected: pilot.projectIds.length, repositoriesScanned: new Set(scopedScans.map(item => item.projectId)).size, prsScanned: new Set(scopedScans.filter(item => item.pullRequest).map(item => item.pullRequest)).size, scansCompleted: scopedScans.filter(item => item.status).length, filesScanned: scopedScans.reduce((sum, item) => sum + item.filesScanned, 0), rulesExecuted: scopedScans.reduce((sum, item) => sum + item.rulesExecuted, 0), findingsGenerated: scopedFindings.length, newFindings: scopedScans.reduce((sum, item) => sum + item.newFindings, 0), criticalFindings: scopedFindings.filter(item => item.severity === 'CRITICAL').length, highFindings: scopedFindings.filter(item => item.severity === 'HIGH').length, findingsResolved: scopedFindings.filter(item => item.status === 'RESOLVED').length, findingsSuppressed: scopedFindings.filter(item => item.status === 'SUPPRESSED').length, acceptedRisks: scopedFindings.filter(item => item.status === 'ACCEPTED_RISK').length, averageRemediationHours: remediation.length ? remediation.reduce((sum, item) => sum + item, 0) / remediation.length : null, medianRemediationHours: remediation.length ? remediation[Math.floor(remediation.length / 2)] : null, aiSystemsDiscovered: scopedScans.reduce((sum, item) => sum + item.aiSystemsDiscovered, 0), shadowAISystems: scopedScans.reduce((sum, item) => sum + item.shadowAISystems, 0), governanceDriftFindings: scopedFindings.filter(item => item.ruleId === 'AI-010').length, technicalControlsWithEvidence: Math.max(0, ...scopedScans.map(item => item.controlsWithEvidence)), falsePositiveRate: classified.length ? falsePositives / classified.length : null, reviewedFindings: classified.length, truePositives, falsePositives };
}
export function calculateRuleQuality(pilotId: string, findings: PilotFinding[]): RuleQuality[] { const scoped = findings.filter(item => item.pilotId === pilotId); return [...new Set(scoped.map(item => item.ruleId))].sort().map(ruleId => { const items = scoped.filter(item => item.ruleId === ruleId); const reviewed = items.filter(item => item.classification); const falsePositives = reviewed.filter(item => item.classification === 'FALSE_POSITIVE').length; return { ruleId, findingsGenerated: items.length, reviewedFindings: reviewed.length, truePositives: reviewed.filter(item => item.classification === 'TRUE_POSITIVE').length, falsePositives, needsReview: reviewed.filter(item => item.classification === 'NEEDS_REVIEW').length, precision: reviewed.length ? (reviewed.length - falsePositives) / reviewed.length : null, suppressionRate: items.length ? items.filter(item => item.status === 'SUPPRESSED').length / items.length : 0, resolutionRate: items.length ? items.filter(item => item.status === 'RESOLVED').length / items.length : 0 }; }); }
export function renderPilotReport(pilot: Pilot, metrics: PilotMetrics, quality: RuleQuality[]): { json: string; html: string } { const disclaimer = 'This report summarizes automated technical analysis and user-reviewed findings. It does not constitute legal advice, certification, attestation, or proof of regulatory compliance.'; const report = { disclaimer, pilot, metrics, ruleQuality: quality }; const html = `<h1>${pilot.name}</h1><p>${disclaimer}</p><h2>Executive Summary</h2><p>${metrics.findingsGenerated} findings across ${metrics.repositoriesScanned} repositories; ${metrics.findingsResolved} resolved.</p><h2>Metrics</h2><pre>${JSON.stringify(metrics, null, 2)}</pre><h2>Rule Quality</h2><pre>${JSON.stringify(quality, null, 2)}</pre>`; return { json: `${JSON.stringify(report, null, 2)}\n`, html: `<!doctype html><html><body>${html}</body></html>` }; }
