import { createHash } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';

export type Severity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type Confidence = 'LOW' | 'MEDIUM' | 'HIGH';
export type Category = 'PII' | 'SECRET' | 'LOGGING' | 'SECURITY' | 'CONFIGURATION' | 'AI';
export type FrameworkMapping = { framework: 'NIST-CSF-2.0'; control: string; relationship: 'related'; explanation: string };
export type Suppression = { ruleId: string; filePath: string; line: number; reason?: string };
export type AIComponent = { id: string; provider: string; technology: string; modelIdentifier?: string; filePath: string; lineNumber: number; discoveryMethod: string; confidence: Confidence; status: 'DISCOVERED' | 'REVIEW_REQUIRED' | 'APPROVED' | 'DEPRECATED'; firstDetected: string; lastDetected: string };
export type Finding = { ruleId: string; ruleVersion?: number; ruleStatus?: 'EXPERIMENTAL' | 'BETA' | 'STABLE'; title: string; description: string; severity: Severity; category: Category; filePath: string; line: number; evidence: string; remediation: string; frameworks: FrameworkMapping[]; confidence: Confidence; fingerprint: string; detectorSignals?: string[] };
export type ScanContext = { filePath: string; content: string; lines: string[]; config: ScannerConfig };
export type Rule = { id: string; version?: number; status?: 'EXPERIMENTAL' | 'BETA' | 'STABLE'; priority?: number; title: string; description: string; category: Category; severity: Severity; confidence: Confidence; frameworks: FrameworkMapping[]; remediation: string; supportedLanguages: string[]; detect: (context: ScanContext) => Finding[] };
export type ScannerConfig = { failOn?: Severity; ignore?: string[]; rules?: Record<string, 'warning' | 'error' | 'off'>; sensitiveFields?: string[]; maxFileSize?: number };
export type Baseline = { version: 1; generatedAt: string; fingerprints: Array<{ fingerprint: string; ruleId: string; filePath: string; line: number }> };
export type ScanResult = { metadata: { scanner: string; version: string; timestamp: string; disclaimer: string }; scannedPath: string; filesScanned: number; skippedFiles: number; malformedSuppressions: number; durationMs: number; rulesExecuted: number; aiComponents: AIComponent[]; findings: Finding[]; suppressedFindings: Array<Finding & { suppression: Suppression }>; baselineFindings: Finding[]; severityCounts: Record<Severity, number>; status: 'PASS' | 'FAILED' };

const VERSION = '0.2.0';
export const severityRank: Record<Severity, number> = { LOW: 1, MEDIUM: 2, HIGH: 3, CRITICAL: 4 };
const extensions = new Set(['.ts', '.tsx', '.js', '.jsx', '.json', '.yaml', '.yml', '.py', '.java', '.properties']);
const ignoredDirectories = new Set(['node_modules', '.git', 'dist', 'build', 'coverage', 'vendor']);
const FRAMEWORKS = {
 data: [{ framework: 'NIST-CSF-2.0' as const, control: 'PR.DS', relationship: 'related' as const, explanation: 'This finding relates to protecting data security.' }],
 access: [{ framework: 'NIST-CSF-2.0' as const, control: 'PR.AA', relationship: 'related' as const, explanation: 'This finding relates to identity and access protection.' }],
 protect: [{ framework: 'NIST-CSF-2.0' as const, control: 'PR.PS', relationship: 'related' as const, explanation: 'This finding relates to platform and configuration protection.' }]
};

export function redact(value: string): string { const trimmed = value.trim(); if (trimmed.length < 8) return '[REDACTED]'; return `${trimmed.slice(0, Math.min(8, Math.ceil(trimmed.length / 3)))}****${trimmed.slice(-3)}`; }
function redactEvidence(value: string): string {
 return value.replace(/((?:postgres|mysql|mongodb(?:\+srv)?):\/\/[^\s/@:]+:)[^\s/@]+(@)/gi, '$1[REDACTED]$2').replace(/(sk_(?:live|test)_)[A-Za-z0-9_-]+/gi, '$1****').replace(/(AKIA)[A-Z0-9]{16}/g, '$1****************').replace(/(bearer\s+)[^\s'"`]+/gi, '$1[REDACTED]').replace(/(password|passwd|secret|token|api[_-]?key|access[_-]?token)\s*[:=]\s*[^,;\s]+/gi, '$1=[REDACTED]').replace(/\b\d{3}-\d{2}-\d{4}\b/g, '[SSN-REDACTED]').replace(/\b(?:\d[ -]*?){13,19}\b/g, '[CARD-REDACTED]').replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi, '[EMAIL-REDACTED]');
}
function isPlaceholder(value: string): boolean { return /(?:your[_ -]?(?:api[_ -]?)?key|example[_ -]?(?:token|key)|dummy[_ -]?(?:password|token)|test[_ -]?(?:secret|password|token)|change[_ -]?me|replace[_ -]?me)/i.test(value); }
function isExamplePublicData(value: string): boolean { return /@(example\.(?:com|org|net|test)|localhost)\b/i.test(value); }
function fingerprint(ruleId: string, filePath: string, line: number, evidence: string): string { return createHash('sha256').update(`${ruleId}\0${filePath}\0${line}\0${evidence.replace(/\s+/g, ' ').trim()}`).digest('hex').slice(0, 24); }
function makeFinding(rule: Rule, context: ScanContext, line: number, evidence: string): Finding { const safeEvidence = redactEvidence(evidence); return { ruleId: rule.id, ruleVersion: rule.version, ruleStatus: rule.status, title: rule.title, description: rule.description, severity: rule.severity, category: rule.category, filePath: context.filePath, line, evidence: safeEvidence, remediation: rule.remediation, frameworks: rule.frameworks, confidence: rule.confidence, fingerprint: fingerprint(rule.id, context.filePath, line, safeEvidence), detectorSignals: [`RULE:${rule.id}`, `CONFIDENCE:${rule.confidence}`] }; }
function isValidCard(value: string): boolean { const digits = value.replace(/\D/g, ''); if (digits.length < 13 || digits.length > 19 || /^0+$/.test(digits)) return false; let sum = 0; let double = false; for (let index = digits.length - 1; index >= 0; index--) { let digit = Number(digits[index]); if (double && (digit *= 2) > 9) digit -= 9; sum += digit; double = !double; } return sum % 10 === 0; }
function linesMatching(rule: Rule, context: ScanContext, pattern: RegExp): Finding[] { return context.lines.flatMap((line, index) => { const extension = path.extname(context.filePath).toLowerCase(); if (/^\s*(?:\/\/|#|\/\*|\*)/.test(line) || (rule.id === 'AI-007' && /ai-governance:\s*registered/i.test(context.content)) || (rule.id === 'PII-004' && !['.json', '.yaml', '.yml', '.properties'].includes(extension)) || ((rule.id === 'SEC-004' || rule.id === 'SEC-006' || rule.id === 'CFG-005') && isPlaceholder(line)) || (rule.id === 'PII-004' && isExamplePublicData(line)) || !pattern.test(line)) return []; if (rule.id === 'PII-002' && !isValidCard(line.match(/(?:\d[ -]*?){13,19}/)?.[0] ?? '')) return []; return [makeFinding(rule, context, index + 1, line)]; }); }
function define(definition: Omit<Rule, 'detect'>, pattern: RegExp): Rule { return { version: 1, status: 'BETA', priority: definition.category === 'SECRET' ? 20 : 10, ...definition, detect: context => linesMatching({ ...definition, detect: () => [] }, context, pattern) }; }
const common = ['TypeScript', 'JavaScript', 'JSON', 'YAML', 'Python', 'Java', 'Properties'];
const baseRules: Rule[] = [
 define({ id: 'SEC-001', title: 'Hardcoded secret', description: 'A provider-style secret is assigned in source.', category: 'SECRET', severity: 'CRITICAL', confidence: 'HIGH', frameworks: FRAMEWORKS.access, remediation: 'Revoke and rotate the value, then load it from a managed secret store.', supportedLanguages: common }, /\bsk_(?:live|test)_[A-Za-z0-9]{8,}\b/),
 define({ id: 'SEC-002', title: 'AWS-style access key', description: 'An AWS-style access key appears in source.', category: 'SECRET', severity: 'CRITICAL', confidence: 'HIGH', frameworks: FRAMEWORKS.access, remediation: 'Revoke the key and use short-lived workload credentials.', supportedLanguages: common }, /\bAKIA[A-Z0-9]{16}\b/),
 define({ id: 'SEC-003', title: 'Private key committed', description: 'Private key material is present in a scanned file.', category: 'SECRET', severity: 'CRITICAL', confidence: 'HIGH', frameworks: FRAMEWORKS.access, remediation: 'Remove and rotate the key; keep private keys outside source control.', supportedLanguages: common }, /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/),
 define({ id: 'SEC-004', title: 'Hardcoded bearer token', description: 'A bearer token is embedded in source.', category: 'SECRET', severity: 'HIGH', confidence: 'HIGH', frameworks: FRAMEWORKS.access, remediation: 'Remove and rotate the token; obtain it at runtime from a secure provider.', supportedLanguages: common }, /\bBearer\s+[A-Za-z0-9._~+/=-]{12,}/i),
 define({ id: 'SEC-005', title: 'Database URL with embedded credentials', description: 'A database URL contains a username and password.', category: 'SECRET', severity: 'CRITICAL', confidence: 'HIGH', frameworks: FRAMEWORKS.access, remediation: 'Inject database credentials at runtime and rotate exposed values.', supportedLanguages: common }, /(?:postgres|mysql|mongodb(?:\+srv)?):\/\/[^\s/@:]+:[^\s/@]+@/i),
 define({ id: 'SEC-006', title: 'Hardcoded password assignment', description: 'A password-like field is assigned a non-placeholder literal.', category: 'SECRET', severity: 'HIGH', confidence: 'HIGH', frameworks: FRAMEWORKS.access, remediation: 'Use environment injection or a managed secret store.', supportedLanguages: common }, /\b(?:password|passwd)\b\s*[:=]\s*['"`][^'"`]{6,}['"`]/i),
 define({ id: 'PII-001', title: 'Potential SSN-like value', description: 'A sensitive field context contains a value resembling a US Social Security number; this is a review signal, not proof of personal data.', category: 'PII', severity: 'HIGH', confidence: 'MEDIUM', frameworks: FRAMEWORKS.data, remediation: 'Remove real identifiers and use synthetic fixtures. Verify the fix by rescanning the same revision.', supportedLanguages: common }, /(?:\bssn\b|social[_-]?security|tax[_-]?id|customer[_-]?identifier|customerSsn)[^\n]*\b\d{3}-\d{2}-\d{4}\b/i),
 define({ id: 'PII-002', title: 'Potential payment-card-like value', description: 'A value resembles a payment card number.', category: 'PII', severity: 'HIGH', confidence: 'MEDIUM', frameworks: FRAMEWORKS.data, remediation: 'Never commit payment data; use provider-approved test tokens.', supportedLanguages: common }, /\b(?:\d[ -]*?){13,19}\b/),
 define({ id: 'PII-003', title: 'Sensitive field stored in plaintext', description: 'A sensitive field is assigned a literal value.', category: 'PII', severity: 'MEDIUM', confidence: 'MEDIUM', frameworks: FRAMEWORKS.data, remediation: 'Minimize retention and protect sensitive fields in an appropriate data store.', supportedLanguages: common }, /\b(?:ssn|social[_-]?security|home[_-]?address|street[_-]?address|cardNumber|creditCard)\b\s*[:=]\s*['"`][^'"`]+['"`]/i),
 define({ id: 'PII-004', title: 'Sensitive data exposed in configuration', description: 'A configuration field contains a sensitive value rather than a reference.', category: 'PII', severity: 'MEDIUM', confidence: 'MEDIUM', frameworks: FRAMEWORKS.data, remediation: 'Move sensitive configuration to protected runtime injection.', supportedLanguages: ['JSON', 'YAML', 'Properties'] }, /(?:ssn|social[_-]?security|email|phone|address|dob|date[_-]?of[_-]?birth)\s*[:=]\s*[^${\s][^,\n]*/i),
 define({ id: 'PII-005', title: 'Potential DOB field with embedded value', description: 'A date-of-birth field has an embedded value.', category: 'PII', severity: 'MEDIUM', confidence: 'MEDIUM', frameworks: FRAMEWORKS.data, remediation: 'Remove personal dates from source and use synthetic fixtures.', supportedLanguages: common }, /\b(?:dob|date[_-]?of[_-]?birth)\b\s*[:=]\s*['"`]?\d{4}[-/]\d{1,2}[-/]\d{1,2}/i),
 define({ id: 'LOG-001', title: 'Password logged', description: 'A logging call includes a password-like field.', category: 'LOGGING', severity: 'HIGH', confidence: 'HIGH', frameworks: FRAMEWORKS.data, remediation: 'Remove credentials from logs or redact them before logging.', supportedLanguages: ['TypeScript', 'JavaScript', 'Java'] }, /(?:console\.(?:log|info|debug|warn)|logger\.(?:info|debug|warn|error)|System\.out\.println)\s*\([^\n]*(?:password|passwd)/i),
 define({ id: 'LOG-002', title: 'Token or API key logged', description: 'A logging call includes a token or API key.', category: 'LOGGING', severity: 'HIGH', confidence: 'HIGH', frameworks: FRAMEWORKS.data, remediation: 'Remove tokens from logs and rotate any exposed credential.', supportedLanguages: ['TypeScript', 'JavaScript', 'Java'] }, /(?:console\.(?:log|info|debug|warn)|logger\.(?:info|debug|warn|error)|System\.out\.println)\s*\([^\n]*(?:token|apiKey|api_key|accessToken)/i),
 define({ id: 'LOG-003', title: 'SSN-like field logged', description: 'A logging call includes an SSN-like field.', category: 'LOGGING', severity: 'HIGH', confidence: 'HIGH', frameworks: FRAMEWORKS.data, remediation: 'Remove identifiers from logs or apply structured redaction.', supportedLanguages: ['TypeScript', 'JavaScript', 'Java'] }, /(?:console\.(?:log|info|debug|warn)|logger\.(?:info|debug|warn|error)|System\.out\.println)\s*\([^\n]*(?:ssn|socialSecurity)/i),
 define({ id: 'LOG-004', title: 'Payment data logged', description: 'A logging call includes a payment-data field.', category: 'LOGGING', severity: 'HIGH', confidence: 'HIGH', frameworks: FRAMEWORKS.data, remediation: 'Do not log payment data; use a tokenized provider reference.', supportedLanguages: ['TypeScript', 'JavaScript', 'Java'] }, /(?:console\.(?:log|info|debug|warn)|logger\.(?:info|debug|warn|error)|System\.out\.println)\s*\([^\n]*(?:cardNumber|creditCard|payment)/i),
 define({ id: 'LOG-005', title: 'Sensitive user object logged', description: 'A user or customer object is logged wholesale and may contain sensitive fields.', category: 'LOGGING', severity: 'MEDIUM', confidence: 'MEDIUM', frameworks: FRAMEWORKS.data, remediation: 'Log an allowlist of non-sensitive fields instead of the whole object.', supportedLanguages: ['TypeScript', 'JavaScript', 'Java'] }, /(?:console\.(?:log|info|debug|warn)|logger\.(?:info|debug|warn|error)|System\.out\.println)\s*\([^\n]*(?:user|customer|account)\s*\)/i),
 define({ id: 'CFG-001', title: 'TLS verification disabled', description: 'TLS certificate verification is explicitly disabled.', category: 'SECURITY', severity: 'HIGH', confidence: 'HIGH', frameworks: FRAMEWORKS.protect, remediation: 'Enable certificate verification and use a trusted CA.', supportedLanguages: common }, /(?:rejectUnauthorized|verify_ssl|tlsVerify|ssl_verify)\s*[:=]\s*(?:false|0)/i),
 define({ id: 'CFG-002', title: 'Permissive CORS', description: 'A wildcard CORS origin may expose responses to arbitrary sites.', category: 'CONFIGURATION', severity: 'MEDIUM', confidence: 'HIGH', frameworks: FRAMEWORKS.protect, remediation: 'Allow only trusted origins.', supportedLanguages: common }, /(?:origin|Access-Control-Allow-Origin)\s*[:=]\s*['"`]\*['"`]/i),
 define({ id: 'CFG-003', title: 'Debug mode enabled', description: 'Debug mode is enabled and may expose implementation details.', category: 'CONFIGURATION', severity: 'MEDIUM', confidence: 'HIGH', frameworks: FRAMEWORKS.protect, remediation: 'Disable debug mode in production.', supportedLanguages: common }, /['"']?\b(?:debug|DEBUG)\b['"']?\s*[:=]\s*(?:true|1|['"`]true['"`])/),
 define({ id: 'CFG-004', title: 'Sensitive HTTP endpoint', description: 'A likely sensitive service endpoint uses plaintext HTTP.', category: 'SECURITY', severity: 'MEDIUM', confidence: 'MEDIUM', frameworks: FRAMEWORKS.protect, remediation: 'Use HTTPS/TLS for service traffic.', supportedLanguages: common }, /http:\/\/[^\s'"`]*(?:api|auth|db|database|internal|service)/i),
 define({ id: 'CFG-005', title: 'Credentials exposed in configuration', description: 'A configuration key contains a hardcoded credential value.', category: 'CONFIGURATION', severity: 'HIGH', confidence: 'HIGH', frameworks: FRAMEWORKS.access, remediation: 'Use a secret manager or runtime environment injection.', supportedLanguages: ['JSON', 'YAML', 'Properties', 'TypeScript', 'JavaScript'] }, /(?:password|passwd|secret|api[_-]?key|access[_-]?token)\s*[:=]\s*['"`][^'"`$]{6,}['"`]/i),
 define({ id: 'CFG-006', title: 'Public cloud storage access', description: 'A cloud-storage policy appears to grant public access.', category: 'CONFIGURATION', severity: 'HIGH', confidence: 'HIGH', frameworks: FRAMEWORKS.protect, remediation: 'Restrict bucket/object access and require authenticated requests.', supportedLanguages: ['JSON', 'YAML', 'Properties'] }, /(?:Principal|principal|public-read|allUsers|storage\.objects\.get)\s*[:=][^\n]*(?:\*|true|allUsers|public-read)/i)
];

const aiFramework = [{ framework: 'NIST-CSF-2.0' as const, control: 'PR.DS', relationship: 'related' as const, explanation: 'This technical signal relates to protecting data sent to an AI service.' }];
const aiRules: Rule[] = [
 define({ id: 'AI-001', title: 'Potential sensitive data sent to AI service', description: 'A known AI call receives a sensitive field or record.', category: 'AI', severity: 'HIGH', confidence: 'MEDIUM', frameworks: aiFramework, remediation: 'Minimize inputs, redact sensitive fields, and document approved data handling.', supportedLanguages: ['TypeScript', 'JavaScript', 'Python'] }, /(?:invoke|chat|generate|complete|createChatCompletion|messages\.create|send)\s*\([^\n]*(?:ssn|password|patient|customer|personal|email|secret|token|record)/i),
 define({ id: 'AI-002', title: 'Credential included in AI input', description: 'A likely credential is passed to an AI request.', category: 'AI', severity: 'CRITICAL', confidence: 'HIGH', frameworks: aiFramework, remediation: 'Never include credentials in prompts or model inputs; rotate exposed values.', supportedLanguages: ['TypeScript', 'JavaScript', 'Python'] }, /(?:invoke|chat|generate|complete|messages\.create|send)\s*\([^\n]*(?:password|secret|token|apiKey|credential)/i),
 define({ id: 'AI-003', title: 'AI request or response logging', description: 'An AI prompt, request, or response may be written to logs.', category: 'AI', severity: 'MEDIUM', confidence: 'HIGH', frameworks: aiFramework, remediation: 'Avoid logging prompts and responses; use secure structured logging with redaction.', supportedLanguages: ['TypeScript', 'JavaScript', 'Python', 'Java'] }, /(?:console\.(?:log|info|debug)|logger\.(?:info|debug|error)|print)\s*\([^\n]*(?:\b(?:prompt|aiResponse|response|messages|request)\b\s*(?:[),;}]|$))/i),
 define({ id: 'AI-004', title: 'Unrestricted user input in AI prompt', description: 'User-controlled input is interpolated directly into an AI request.', category: 'AI', severity: 'MEDIUM', confidence: 'MEDIUM', frameworks: aiFramework, remediation: 'Constrain and validate user input before model invocation; separate instructions from data.', supportedLanguages: ['TypeScript', 'JavaScript', 'Python'] }, /(?:invoke|chat|generate|complete|messages\.create)\s*\([^\n]*(?:req\.body|request\.body|userInput|user_input|query)/i),
 define({ id: 'AI-005', title: 'AI output used without visible validation', description: 'AI output flows directly into a security-sensitive operation.', category: 'AI', severity: 'HIGH', confidence: 'MEDIUM', frameworks: aiFramework, remediation: 'Validate and constrain model output before database, shell, URL, or code execution.', supportedLanguages: ['TypeScript', 'JavaScript', 'Python'] }, /(?:exec|spawn|eval|query|fetch)\s*\([^\n]*(?:response|completion|output|result)/i),
 define({ id: 'AI-006', title: 'AI model identifier not explicit', description: 'An AI client is initialized without a visible model identifier.', category: 'AI', severity: 'LOW', confidence: 'LOW', frameworks: aiFramework, remediation: 'Declare the approved model through configuration and include it in governance review.', supportedLanguages: ['TypeScript', 'JavaScript', 'Python'] }, /new\s+(?:OpenAI|Anthropic|ChatOpenAI|GoogleGenerativeAI)\s*\(\s*\)/i),
 define({ id: 'AI-007', title: 'AI integration lacks governance metadata', description: 'AI SDK usage was found but no nearby governance declaration is visible.', category: 'AI', severity: 'MEDIUM', confidence: 'LOW', frameworks: aiFramework, remediation: 'Register the component with owner, purpose, data handling, and review status.', supportedLanguages: common }, /(?:from\s+['"](?:openai|@anthropic-ai|langchain|llamaindex|@google\/generative-ai)|import\s+(?:openai|anthropic|boto3|transformers))/i),
 define({ id: 'AI-008', title: 'AI-generated URL fetched without validation', description: 'A model result appears to be used as a network URL without an allowlist.', category: 'AI', severity: 'HIGH', confidence: 'MEDIUM', frameworks: aiFramework, remediation: 'Validate scheme, host, and destination against an explicit allowlist before fetching.', supportedLanguages: ['TypeScript', 'JavaScript', 'Python'] }, /fetch\s*\([^\n]*(?:aiResponse|completion|modelOutput|generatedUrl)/i),
 define({ id: 'AI-009', title: 'AI output used as executable code', description: 'A model result appears to reach eval-like execution.', category: 'AI', severity: 'CRITICAL', confidence: 'HIGH', frameworks: aiFramework, remediation: 'Never execute model output directly; use a constrained parser and human review.', supportedLanguages: ['TypeScript', 'JavaScript', 'Python'] }, /(?:eval|Function)\s*\([^\n]*(?:response|completion|output|result)/i),
 define({ id: 'AI-010', title: 'AI output reaches customer-facing operation', description: 'An AI result appears to flow directly to an external user operation.', category: 'AI', severity: 'MEDIUM', confidence: 'MEDIUM', frameworks: aiFramework, remediation: 'Add human review or explicit output validation before customer-facing actions.', supportedLanguages: ['TypeScript', 'JavaScript', 'Python'] }, /(?:sendEmail|send_message|notifyUser|customerResponse)\s*\([^\n]*(?:response|completion|output|result)/i)
];
const rules: Rule[] = [...baseRules, ...aiRules];

export function getRules(config: ScannerConfig = {}): Rule[] { return rules.filter(item => config.rules?.[item.id] !== 'off'); }
export function getRule(id?: string): Rule[] { return id ? rules.filter(item => item.id === id) : rules; }
export function discoverAIComponents(content: string, filePath: string): AIComponent[] {
 const patterns: Array<[RegExp, string, string]> = [[/(?:from\s+['"]openai|import\s+openai|new\s+OpenAI)/i, 'OpenAI', 'OpenAI SDK'], [/(?:from\s+['"]@anthropic-ai|import\s+anthropic|new\s+Anthropic)/i, 'Anthropic', 'Anthropic SDK'], [/(?:from\s+['"]@google\/generative-ai|import\s+['"]?GoogleGenerativeAI|new\s+GoogleGenerativeAI)/i, 'Google', 'Gemini SDK'], [/(?:from\s+['"]boto3|import\s+boto3|BedrockRuntime|new\s+Bedrock)/i, 'AWS', 'Bedrock SDK'], [/(?:from\s+['"]transformers|import\s+transformers|HuggingFace)/i, 'Hugging Face', 'Hugging Face library'], [/(?:from\s+['"]langchain|import\s+langchain|new\s+LangChain)/i, 'LangChain', 'LangChain'], [/(?:from\s+['"](?:llamaindex|llama_index)|import\s+(?:llamaindex|llama_index)|new\s+LlamaIndex)/i, 'LlamaIndex', 'LlamaIndex'], [/(?:from\s+['"]ollama|import\s+ollama|new\s+Ollama|localModel|local_model)/i, 'Local model', 'Local model integration']]; const now = new Date().toISOString(); const found: AIComponent[] = [];
 content.split(/\r?\n/).forEach((line, index) => { if (/^\s*(?:\/\/|#|\/\*|\*)/.test(line)) return; const match = patterns.find(([pattern]) => pattern.test(line)); if (!match) return; const model = line.match(/(?:model|modelName|model_name)\s*[:=]\s*['"`]([^'"`]+)['"`]/i)?.[1]; const id = createHash('sha256').update(`${filePath}:${index + 1}:${match[1]}`).digest('hex').slice(0, 20); found.push({ id, provider: match[1], technology: match[2], modelIdentifier: model, filePath, lineNumber: index + 1, discoveryMethod: 'active-import-or-config', confidence: 'HIGH', status: 'REVIEW_REQUIRED', firstDetected: now, lastDetected: now }); }); return found;
}
export function severityCounts(findings: Finding[]): Record<Severity, number> { return findings.reduce((counts, item) => { counts[item.severity]++; return counts; }, { LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0 }); }
export function parseSuppressions(content: string, filePath: string): { suppressions: Suppression[]; malformed: string[] } {
 const suppressions: Suppression[] = []; const malformed: string[] = [];
 content.split(/\r?\n/).forEach((line, index) => { if (!line.toLowerCase().includes('compliance-ignore')) return; const match = line.match(/compliance-ignore\s+([A-Z]+-\d{3})(?:\s+reason:\s*(.*?))?\s*(?:\*\/)?\s*$/i); if (!match) malformed.push(`line ${index + 1}`); else suppressions.push({ ruleId: match[1].toUpperCase(), filePath, line: index + 1, reason: match[2]?.trim() || undefined }); });
 return { suppressions, malformed };
}
function shouldIgnore(relativePath: string, config: ScannerConfig): boolean { return [...ignoredDirectories, ...(config.ignore ?? [])].some(pattern => relativePath === pattern || relativePath.startsWith(`${pattern}/`) || relativePath.includes(pattern)); }
async function collectFiles(root: string, current: string, config: ScannerConfig, result: string[], skipped: { count: number }): Promise<void> {
 for (const entry of await fs.readdir(current, { withFileTypes: true })) { const absolute = path.join(current, entry.name); const relative = path.relative(root, absolute).split(path.sep).join('/'); if (shouldIgnore(relative, config)) continue; if (entry.isDirectory()) await collectFiles(root, absolute, config, result, skipped); else if (entry.isSymbolicLink()) skipped.count++; else if (extensions.has(path.extname(entry.name)) || entry.name === '.env.example') { const stat = await fs.stat(absolute); if (stat.size <= (config.maxFileSize ?? 1024 * 1024)) result.push(absolute); else skipped.count++; } }
}
export async function scanDirectory(scanPath: string, config: ScannerConfig = {}, baseline?: Baseline): Promise<ScanResult> {
 const started = Date.now(); const root = path.resolve(scanPath); const stat = await fs.stat(root); const files: string[] = []; const skipped = { count: 0 }; if (stat.isDirectory()) await collectFiles(root, root, config, files, skipped); else if (stat.size <= (config.maxFileSize ?? 1024 * 1024)) files.push(root); else skipped.count++;
 const findings: Finding[] = []; const suppressedFindings: Array<Finding & { suppression: Suppression }> = []; const aiComponents: AIComponent[] = []; let malformedSuppressions = 0;
 for (const file of files) { const content = await fs.readFile(file, 'utf8'); if (content.includes('\0')) { skipped.count++; continue; } const relative = path.relative(process.cwd(), file).split(path.sep).join('/') || path.basename(file); const context: ScanContext = { filePath: relative, content, lines: content.split(/\r?\n/), config }; aiComponents.push(...discoverAIComponents(content, relative)); const parsed = parseSuppressions(content, relative); malformedSuppressions += parsed.malformed.length; const detected = getRules(config).flatMap(current => current.detect(context)); for (const item of detected) { const suppression = parsed.suppressions.find(entry => entry.ruleId === item.ruleId && (entry.line === item.line || entry.line + 1 === item.line)); if (suppression) suppressedFindings.push({ ...item, suppression }); else findings.push(item); } }
 const baselineFingerprints = new Set(baseline?.fingerprints.map(item => item.fingerprint) ?? []); const baselineFindings = findings.filter(item => baselineFingerprints.has(item.fingerprint)); const active = findings.filter(item => !baselineFingerprints.has(item.fingerprint)); const counts = severityCounts(active); const threshold = config.failOn ?? 'HIGH';
 return { metadata: { scanner: 'Compliance-as-Code', version: VERSION, timestamp: new Date().toISOString(), disclaimer: 'Technical findings are potential risks for review and do not certify legal or regulatory compliance.' }, scannedPath: scanPath, filesScanned: files.length, skippedFiles: skipped.count, malformedSuppressions, durationMs: Date.now() - started, rulesExecuted: files.length * getRules(config).length, aiComponents, findings: active, suppressedFindings, baselineFindings, severityCounts: counts, status: active.some(item => severityRank[item.severity] >= severityRank[threshold]) ? 'FAILED' : 'PASS' };
}
export function createBaseline(result: ScanResult): Baseline { return { version: 1, generatedAt: new Date().toISOString(), fingerprints: [...result.findings, ...result.baselineFindings, ...result.suppressedFindings].map(item => ({ fingerprint: item.fingerprint, ruleId: item.ruleId, filePath: item.filePath, line: item.line })) }; }
export function renderJson(result: ScanResult): string { return `${JSON.stringify(result, null, 2)}\n`; }
export function renderSarif(result: ScanResult): string { const metadata = [...new Map(getRule().map(item => [item.id, { id: item.id, name: item.title, shortDescription: { text: item.description }, help: { text: item.remediation }, properties: { severity: item.severity, confidence: item.confidence } }])).values()]; const results = [...result.findings, ...result.suppressedFindings].map(item => ({ ruleId: item.ruleId, level: item.severity === 'LOW' ? 'note' : item.severity === 'MEDIUM' ? 'warning' : 'error', message: { text: `${item.title}: ${item.remediation}` }, locations: [{ physicalLocation: { artifactLocation: { uri: item.filePath }, region: { startLine: item.line } } }] })); return `${JSON.stringify({ version: '2.1.0', $schema: 'https://json.schemastore.org/sarif-2.1.0.json', runs: [{ tool: { driver: { name: 'Compliance-as-Code', version: VERSION, rules: metadata } }, results }] }, null, 2)}\n`; }
export function renderConsole(result: ScanResult, quiet = false): string { if (quiet) return `Result: ${result.status}\n`; const lines = ['Compliance-as-Code', '', `Scanning: ${result.scannedPath}`, `Files scanned: ${result.filesScanned}`, `Skipped files: ${result.skippedFiles}`, `Duration: ${result.durationMs} ms`, '']; for (const severity of ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as Severity[]) { const group = result.findings.filter(item => item.severity === severity); if (!group.length) continue; lines.push(severity); for (const item of group) lines.push(`${item.ruleId} ${item.title}`, `  ${item.filePath}:${item.line}`, `  Remediation: ${item.remediation}`, `  Framework: ${item.frameworks.map(map => `${map.framework} ${map.control}`).join(', ')}`, ''); } lines.push('Summary', `Critical: ${result.severityCounts.CRITICAL}`, `High: ${result.severityCounts.HIGH}`, `Medium: ${result.severityCounts.MEDIUM}`, `Low: ${result.severityCounts.LOW}`, `Suppressed: ${result.suppressedFindings.length}`, `Malformed suppressions: ${result.malformedSuppressions}`, `Baselined: ${result.baselineFindings.length}`, '', `Result: ${result.status}`); return `${lines.join('\n')}\n`; }
export { rules };
