#!/usr/bin/env node
import { promises as fs } from 'node:fs';
import { resolve } from 'node:path';
import { createBaseline, getRule, renderConsole, renderJson, renderSarif, scanDirectory, type Baseline, type ScannerConfig, type Severity } from '../../../packages/compliance-core/src/index.js';

const args = process.argv.slice(2); const VERSION = '0.2.0';
function valueAfter(flag: string): string | undefined { const index = args.indexOf(flag); return index >= 0 ? args[index + 1] : undefined; }
function usage(): void { console.log(`Compliance-as-Code ${VERSION}\n\nUsage:\n  compliance-check [path] [options]\n  compliance-check rules [RULE-ID]\n\nOptions:\n  --format console|json|sarif\n  --fail-on low|medium|high|critical\n  --config <file>\n  --baseline <file>\n  --create-baseline <file>\n  --ignore <path>\n  --max-file-size <bytes>\n  --quiet\n  --help, --version`); }
if (args.includes('--help') || args.includes('-h')) { usage(); process.exit(0); }
if (args.includes('--version') || args.includes('-v')) { console.log(VERSION); process.exit(0); }
if (args[0] === 'rules') { const selected = getRule(args[1]); if (args[1] && !selected.length) { console.error(`Unknown rule: ${args[1]}`); process.exit(2); } for (const rule of selected) console.log(`${rule.id} v${rule.version ?? 1} | ${rule.title} | ${rule.category} | ${rule.severity} | ${rule.confidence} | ${rule.status ?? 'BETA'}\n  ${rule.description}\n  Languages: ${rule.supportedLanguages.join(', ')}\n  Remediation: ${rule.remediation}\n  Mapping: ${rule.frameworks.map(item => `${item.framework} ${item.control}`).join(', ')}\n`); process.exit(0); }
if (args[0] === 'explain') { const rule = getRule(args[1])[0]; if (!rule) { console.error(`Unknown rule: ${args[1] ?? '(missing)'}`); process.exit(2); } console.log(`${rule.id} v${rule.version ?? 1} - ${rule.title}\n\nStatus: ${rule.status ?? 'BETA'}\nSeverity: ${rule.severity} (potential impact)\nConfidence: ${rule.confidence} (detector certainty)\n\n${rule.description}\n\nWhy it matters: Review the matched code and determine whether the technical condition is intended.\n\nRemediation: ${rule.remediation}\n\nFramework mappings: ${rule.frameworks.map(item => `${item.framework} ${item.control}: ${item.explanation}`).join('\n')}\n\nKnown limitation: Static pattern detection can produce false positives and cannot prove runtime behavior.`); process.exit(0); }
const valueFlags = new Set(['--format', '--fail-on', '--config', '--baseline', '--create-baseline', '--ignore', '--max-file-size', '--output']);
const scanPath = args.find((arg, index) => !arg.startsWith('-') && !valueFlags.has(args[index - 1] ?? '')) ?? '.'; const format = (valueAfter('--format') ?? 'console') as 'console' | 'json' | 'sarif'; const failOn = (valueAfter('--fail-on') ?? 'high').toUpperCase() as Severity;
if (!['console', 'json', 'sarif'].includes(format) || !['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].includes(failOn)) { console.error('Invalid format or severity. Use --help for usage.'); process.exit(2); }
async function main(): Promise<void> {
 let config: ScannerConfig = { failOn, ignore: [] }; const configPath = valueAfter('--config') ?? 'compliance.config.json';
 try { config = { ...JSON.parse(await fs.readFile(resolve(configPath), 'utf8')), failOn }; } catch { if (valueAfter('--config')) throw new Error(`Unable to read config: ${configPath}`); }
 config.failOn = failOn; config.ignore = [...(config.ignore ?? []), ...args.flatMap((arg, index) => arg === '--ignore' && args[index + 1] ? [args[index + 1]] : [])]; const max = valueAfter('--max-file-size'); if (max) config.maxFileSize = Number(max);
 let baseline: Baseline | undefined; const baselinePath = valueAfter('--baseline'); if (baselinePath) baseline = JSON.parse(await fs.readFile(resolve(baselinePath), 'utf8')) as Baseline;
 const result = await scanDirectory(scanPath, config, baseline); const createPath = valueAfter('--create-baseline'); if (createPath) await fs.writeFile(resolve(createPath), `${JSON.stringify(createBaseline(result), null, 2)}\n`);
 if (args.includes('--upload')) { const apiUrl = process.env.COMPLIANCE_API_URL; const projectId = process.env.COMPLIANCE_PROJECT_ID; const apiToken = process.env.COMPLIANCE_API_TOKEN; if (!apiUrl || !projectId || !apiToken) throw new Error('COMPLIANCE_API_URL, COMPLIANCE_PROJECT_ID, and COMPLIANCE_API_TOKEN are required for --upload'); const response = await fetch(`${apiUrl.replace(/\/$/, '')}/api/scans`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${apiToken}` }, body: JSON.stringify({ projectId, result, metadata: { repository: process.env.GITHUB_REPOSITORY, branch: process.env.GITHUB_REF_NAME, commitSha: process.env.GITHUB_SHA, pullRequest: process.env.GITHUB_EVENT_NUMBER, workflowRun: process.env.GITHUB_RUN_ID } }) }); if (!response.ok) throw new Error(`API upload failed (${response.status})`); }
 const output = args.includes('--validation-mode') ? JSON.stringify({ scannedPath: result.scannedPath, filesScanned: result.filesScanned, findings: result.findings.length, severityCounts: result.severityCounts, rulesTriggered: [...new Set(result.findings.map(item => item.ruleId))], highConfidence: result.findings.filter(item => item.confidence === 'HIGH').length, mediumConfidence: result.findings.filter(item => item.confidence === 'MEDIUM').length, lowConfidence: result.findings.filter(item => item.confidence === 'LOW').length, durationMs: result.durationMs, disclaimer: 'Local validation summary only; source and evidence are not uploaded.' }, null, 2) + '\n' : format === 'json' ? renderJson(result) : format === 'sarif' ? renderSarif(result) : renderConsole(result, args.includes('--quiet')); if (args.includes('--profile')) process.stderr.write(`Profile: files=${result.filesScanned}, duration=${result.durationMs}ms, files/sec=${result.durationMs ? (result.filesScanned / (result.durationMs / 1000)).toFixed(1) : 'n/a'}\n`); const outputPath = valueAfter('--output'); if (outputPath) await fs.writeFile(resolve(outputPath), output); else process.stdout.write(output); if (result.status === 'FAILED') process.exitCode = 1;
}
main().catch(error => { console.error(`Scan failed: ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 2; });
